export enum InputResourceType {
    TOURNESOL = "tournesol",
    OLIVE = "olive",
    CANOLA = "canola",
    RIZ = "riz",
    PEUPLIER = "peuplier",
    PLANCHES = "planches",
    BLE = "blé",
    ORGE = "orge",
    SORGHO = "sorgho",
    BETTERAVE = "betterave",
    CANNE_A_SUCRE = "canne à sucre",
    COTON = "coton",
    TISSU = "tissu",
    SUCRE = "sucre",
    FARINE = "farine",
    POMME_DE_TERRE = "pomme de terre",
    HUILE = "huile",
    RAISIN = "raisin",
}
