export enum OutputResourceType {
    HUILE = "huile",
    PLANCHES = "planches",
    WAGONS = "wagons",
    JOUETS = "jouets",
    FARINE = "farine",
    SUCRE = "sucre",
    TISSU = "tissu",
    VETEMENTS = "vêtements",
    GATEAU = "gâteau",
    CHIPS = "chips",
    VIN = "vin",
    FERTILISANT = "fertilizant",
    LAIT_STERILISE = "lait stérélisé",
    BEURRE = "beurre",
}
